### ISSUE TITLE
Services compatibility (docker-compose)

### ISSUE THREAD

**Issue by leokun** [iamluc/docker-hostmanager#36]
Bonjour Luc :)

I recently discover you amazing tool, but it only works partially for me.
I am using docker-compose with `version: '2'` and 'services. But it doesn't take the `DOMAIN_NAME` from environment.

for exeample: 
given 
```yaml
version: '2'

services:

  app:
    container_name: my_app
    image: 5.3.29-apache
    ports :
      - 80:80
    environment: 
     - DOMAIN_NAME=www.myapp.com
```

my hosts file will look like : 
```
172.18.0.3 app.foldername_default 25e65f49.foldername_default foldername_app.foldername_default
```

Is there any solution to use the domainname env in this example and maybe take also the `container_name` ?

I tried to take a look at your code, but it's too complicated for me to fix it myself.

Merci beaucoup pour ton aide.
Léo
